In [2]:
import torch

In [3]:
device = torch.device("cuda")

In [4]:
A = torch.arange(20,dtype=torch.float32,device=device).reshape(5,4)

In [5]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], device='cuda:0')

In [6]:
B = A.clone()

In [7]:
A+B

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]], device='cuda:0')

In [8]:
## Hadamard Product
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]], device='cuda:0')

In [9]:
a = 2
X = torch.arange(24,device=device).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], device='cuda:0')

In [10]:
a+X

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]], device='cuda:0')

In [11]:
a*X

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]], device='cuda:0')

In [12]:
## 几个常见的降维(dimention reduction)方法  
### Sum
A.sum()

tensor(190., device='cuda:0')

In [13]:
## Mean or Average
A.mean()

tensor(9.5000, device='cuda:0')

In [14]:
## Number
A.numel()

20

In [15]:
A.mean() == A.sum()/A.numel()

tensor(True, device='cuda:0')

In [16]:
## 非降维求和
sum_A = A.sum(axis=1,keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]], device='cuda:0')

In [17]:
## Broadcastimg Mechanism 广播机制
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]], device='cuda:0')

In [21]:
### dot product
x = torch.arange(4,dtype=torch.float32,device=device)
y = torch.ones(4,dtype=torch.float32,device=device)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.], device='cuda:0'),
 tensor([1., 1., 1., 1.], device='cuda:0'),
 tensor(6., device='cuda:0'))